---
title: "Untitled"
author: "Myles Thomas"
date: "1/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```




```{r}
# Load libraries
library(tidyverse)
library(gt)
library(tidymodels)
library(ggthemes)
library(ggtext)
library(stringi)
library(gt)
library(rmarkdown)
library(rlang)
options(scipen = 99999)


# get ncaa data
#team <- readr::read_csv("../data/ncaaw/team.csv") %>% janitor::clean_names() %>% dplyr::mutate(date = lubridate::dmy(date)) %>%
#  mutate(points_difference = points_expected - points_scored)
player <- readr::read_csv("../data/ncaaw/player.csv") %>% janitor::clean_names() %>% dplyr::mutate(date = lubridate::dmy(date))
team_accurate_game_stats <- readr::read_csv("../data/ncaaw/s3/RUNNING_Adj_full_team_stats.csv") %>%
  janitor::clean_names() %>%
  dplyr::mutate(date = lubridate::dmy(date)) %>%
  rename(points_expected = sq_points,
         points_scored = points) %>%
  mutate(points_difference = points_expected - points_scored) %>%
  select(teams:possessions, points_expected, points_scored, points_difference, date, game_id)

t1 <- team_accurate_game_stats %>%
  arrange(game_id, teams)
t2 <- team_accurate_game_stats %>%
  arrange(game_id, dplyr::desc(teams)) %>%
  rename(opponent = teams) %>%
  select(c(opponent, points_scored, points_expected)) %>%
  rename("points_allowed" = points_scored,
         "points_allowed_expected" = points_expected)
matchups <- dplyr::bind_cols(t1, t2) %>%
  mutate(game_mov = points_scored - points_allowed) %>%
  mutate(game_mov_expected = points_expected - points_allowed_expected) %>%
  mutate(win = ifelse(game_mov > 0, 1, 0),
         win_expectation = ifelse(game_mov_expected > 0, 1, 0))

yesterday <- lubridate::today() - 1
asp_ratio <- 16/9
lower_bound <- .05
upper_bound <- .95


# Files with team logos, colors, etc
ncaa_teams <- readr::read_csv("C:/Users/Myles/OneDrive/Documents/GitHubThings/ShotQualityResearch/a/ncaa-teams.csv")
ncaa_logos <- readr::read_csv("C:/Users/Myles/OneDrive/Documents/GitHubThings/ShotQualityResearch/a/ncaa-logos.csv")
power_five_names <- c("ACC", "Big 12", "Big Ten", "Pac-12", "SEC")

running_player <- readr::read_csv("../data/ncaaw/extras/Running_Player_Analysis.csv") %>%
  janitor::clean_names() %>%
  dplyr::mutate(date = lubridate::dmy(date)) %>%
  mutate_at("players", Upper_Case_Names) %>%
  mutate(good_pos_rate = good_possessions / (good_possessions + bad_possessions))

# GT functions
gt_theme_538 <- function(data,...) {
  data %>%
  opt_all_caps()  %>%
  opt_table_font(
    font = list(
      google_font("Chivo"),
      default_fonts()
    )
  ) %>%
    tab_style(
      style = cell_borders(
        sides = "bottom", color = "transparent", weight = px(2)
      ),
      locations = cells_body(
        columns = everything(),
        # This is a relatively sneaky way of changing the bottom border
        # Regardless of data size
        rows = nrow(data$`_data`)
      )
    )  %>% 
  tab_options(
    column_labels.background.color = "white",
    table.border.top.width = px(3),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    column_labels.border.top.width = px(3),
    column_labels.border.top.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "black",
    data_row.padding = px(3),
    source_notes.font.size = 12,
    table.font.size = 16,
    heading.align = "left",
    ...
  ) 
}

gt_theme_espn <- function(data, ...){
  data %>% 
    opt_all_caps()  %>%
    opt_table_font(
      font = list(
        google_font("Lato"),
        default_fonts()
      )
    )  %>% 
    opt_row_striping() %>% 
    tab_options(
      row.striping.background_color = "#fafafa",
      table_body.hlines.color = "#f6f7f7",
      source_notes.font.size = 12,
      table.font.size = 16,
      table.width = px(925),
      heading.align = "left",
      heading.title.font.size = 24,
      table.border.top.color = "transparent",
      table.border.top.width = px(3),
      data_row.padding = px(7),
      ...
    ) 
}

# Set a theme
theme_set(theme_bw() +
            theme_fivethirtyeight() +
            theme(plot.title = element_text(face = "bold", size = 28/.pt, hjust = 0),
                  plot.subtitle = element_text(face = "italic", size = 24/.pt),
                  strip.background = element_rect(color = "black", fill = "#C0C0C0", size = 3.5, linetype = "blank"),
                  strip.text = element_text(face = "bold", size = 24/.pt),
                  panel.grid.minor.x = element_blank(),
                  panel.grid.minor.y = element_blank(),
                  panel.border = element_blank(),
                  axis.ticks = element_blank(),
                  axis.text = element_text(size = 24/.pt),
                  axis.title = element_text(face = "bold", size = 26/.pt),
                  plot.caption = element_text(face = "italic", size = 20/.pt),
                  legend.title = element_text(size = 24/.pt),
                  legend.text = element_text(size = 20/.pt),
                  legend.key.size = unit(0.75, "lines")))

th <- theme_fivethirtyeight() +
  theme_classic() + 
  theme(
    plot.title = element_text(face = "bold", size = 24),
    plot.subtitle = element_text(size = 18, face = "italic"),
    plot.caption = element_markdown(size = 12, face = "italic"),
    axis.text = element_text(size = 12),
    axis.title.y = element_text(size = 12, angle = 0, vjust = .5), # vjust = location on (0, 1)
    axis.title.x = element_text(size = 12), # vjust = location on (0, 1)
    aspect.ratio = 1/asp_ratio,
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    strip.background = element_rect(color = "black", fill = "#C0C0C0", size = 3.5, linetype = "blank")
  
      column_labels.background.color = "white",
      column_labels.font.weight = "bold",
      table.border.top.width = px(3),
      table.border.top.color = "transparent",
      table.border.bottom.color = "transparent",
      table.border.bottom.width = px(3),
      column_labels.border.top.width = px(3),
      column_labels.border.top.color = "transparent",
      column_labels.border.bottom.width = px(3),
      column_labels.border.bottom.color = "black",
      data_row.padding = px(3),
      source_notes.font.size = 12,
      table.font.size = 16,
      heading.align = "right"
    ) %>%
    opt_table_font(font = list(default_fonts())) %>%
  tab_style(style = cell_borders(sides = "left", color = "black", weight = px(3)),
    locations = list(cells_body(columns = 1), cells_column_labels(1))) 

gt2

# save
gt::gtsave(data = gt2,
           filename = "right-side.png",
           path = "C:/Users/Myles/OneDrive/Documents/GitHubThings/ShotQualityResearch/viz")
```


3PT over exp:

```{r}
d <- player %>%
  filter(date == yesterday) %>%
  left_join(ncaa_logos) %>%
  mutate(x3pt_makes_expected = x3pt_fg_percent_expected*x3pt_attempts,
         x3pt_makes_scored = x3pt_fg_percent*x3pt_attempts,
         x3pt_makes_difference = x3pt_makes_expected - x3pt_makes_scored) %>%
  arrange(x3pt_makes_difference) %>%
  slice(1:15)

d
```



```{r}
gt <- d %>%
  mutate_if(is.numeric, function(x) {round(x, 2)}) %>%
  select(-c(points_expected, points_scored, points_difference)) %>%
  rename(points_expected = x3pt_makes_expected,
         points_scored = x3pt_makes_scored,
         points_difference = x3pt_makes_difference) %>%
  select(logo, players, points_expected:points_difference) %>%
  gt() %>%
  text_transform(
      locations = cells_body(c(logo)),
      fn = function(x) {
        purrr::map_chr(x, ~ local_image(
          filename = as.character(.x),
          height = 30
        ))}) %>%
  cols_label(
    logo = "",
    players = "",
    points_expected = "Expected",
    points_scored = "Scored",
    points_difference = "Difference"
  ) %>%
  tab_source_note(
    source_note = md("<br>Figure: @Shot_Quality")
  )  %>%
  tab_header(title = md("**ShotQuality discrepancies: 3PT Made**"),
             subtitle = md(glue::glue("Games played on {format(yesterday, '%m-%d-%y')}"))) %>%
  gt_theme_538() %>%
  data_color(
    columns = c(points_difference),
    colors = scales::col_numeric(
      domain = c(-5, 5),
      alpha = .85,
      palette = c("#ff2700", "#f8fcf8", "#44ab43")  
    )) %>%
  tab_spanner(
    label = "ShotQuality Metrics",
    columns = c(points_expected:points_difference)
  ) %>%
  tab_spanner(
    label = "Player",
    columns = c(logo:players)
  )

gt

gt::gtsave(data = gt,
           filename = "womens-3pt-shooting.png",
           path = "C:/Users/Myles/OneDrive/Documents/GitHubThings/ShotQualityResearch/viz")
```



Caitlin Clark analysis:

```{r}
# Getting opponents for each game
school_name <- "Iowa"
player_name <- "Caitlin Clark"

opponents <- team_accurate_game_stats %>%
  rename(games_ids = game_id,
         opponent = teams) %>%
  select(games_ids, opponent) %>%
  filter(opponent != school_name) %>%
  left_join(ncaa_logos, by = c("opponent" = "logos")) %>%
  rename(opponent_logo = logo) %>%
  select(games_ids, opponent, opponent_logo)
opponents

d <- player %>%
  filter(players == player_name) %>%
  left_join(opponents) %>%
  left_join(ncaa_logos) %>%
  select(logo, opponent_logo, date, points_expected, points_scored, points_difference)

d %>%
  select(date:points_difference)
```

```{r}
gt <- d %>%
  mutate_if(is.numeric, function(x) {round(x, 2)}) %>%
  arrange(date) %>%
  gt() %>%
  text_transform(
      locations = cells_body(c(logo)),
      fn = function(x) {
        purrr::map_chr(x, ~ local_image(
          filename = as.character(.x),
          height = 30
        ))}) %>%
  text_transform(
      locations = cells_body(c(opponent_logo)),
      fn = function(x) {
        purrr::map_chr(x, ~ local_image(
          filename = as.character(.x),
          height = 30
        ))}) %>%
  cols_label(
    logo = "",
    date = "",
    opponent_logo = "",
    points_expected = "Expected",
    points_scored = "Actual",
    points_difference = "Difference"
  ) %>%
  tab_source_note(
    source_note = md("<br>Figure: @Shot_Quality")
  )  %>%
  tab_header(title = md(glue::glue("**ShotQuality discrepancies: {player_name}**")),
             subtitle = md("2021-2022 Season")) %>%
  gt_theme_538() %>%
  data_color(
    columns = c(points_difference),
    colors = scales::col_numeric(
      domain = c(-16, 16),
      alpha = .95,
      palette = c("#ff2700", "#f8fcf8", "#44ab43")  
    )) %>%
  tab_spanner(
    label = "ShotQuality Metrics",
    columns = c(points_expected:points_difference)
  ) %>%
  tab_spanner(
    label = "Matchup",
    columns = c(logo:date)
  )

gt

gt::gtsave(data = gt,
           filename = "caitlin-clark.png",
           path = "C:/Users/Myles/OneDrive/Documents/GitHubThings/ShotQualityResearch/viz")
```

Ayoka Lee:

```{r}
running_player <- readr::read_csv("../data/ncaaw/extras/Running_Player_Analysis.csv") %>%
  janitor::clean_names() %>%
  dplyr::mutate(date = lubridate::dmy(date)) %>%
  mutate(good_pos_rate = good_possessions / (good_possessions + bad_possessions))
running_player

d <- running_player %>%
  arrange(desc(sq_points)) %>%
  left_join(ncaa_logos) %>%
  mutate_at("players", Upper_Case_Names)
d
```
```{r}
domain1 <- c(quantile(running_player$good_pos_rate, .05, na.rm = T),
             quantile(running_player$good_pos_rate, .95, na.rm = T))

gt <- d %>%
  mutate_at(c("sq_ppp", "sq_points"), function(x) {round(x, 2)}) %>%
  select(logo, players, date, possessions, points, sq_points, sq_ppp, good_pos_rate) %>%
  dplyr::slice(1:15) %>%
  gt() %>%
  text_transform(
      locations = cells_body(c(logo)),
      fn = function(x) {
        purrr::map_chr(x, ~ local_image(
          filename = as.character(.x),
          height = 30
        ))}) %>%
  cols_label(
    logo = "",
    players = "",
    date = "Date",
    points = " Actual Points",
    sq_points = "Expected Points",
    possessions = "Possessions",
    good_pos_rate = "Good Possession Rate",
    # sq_passing_points_created = "SQ Passing Points"
    sq_ppp = "SQ PPP"
  ) %>%
  tab_source_note(
    source_note = md("<br>Figure: @Shot_Quality")
  )  %>%
  tab_header(title = md("**Top Scoring Performances: What were the Quality of Possessions?**"),
             subtitle = md(glue::glue("2021-2022 Season"))) %>%
  gt_theme_538() %>%
  data_color(
    columns = c(good_pos_rate),
    colors = scales::col_numeric(
      domain = domain1,
      palette = c("#ff2700", "#f8fcf8", "#44ab43")  
    )) %>%
  tab_spanner(
    label = "ShotQuality Metrics",
    columns = c(possessions:good_pos_rate)) %>%
  tab_spanner(
    label = "Player",
    columns = c(logo:date)) %>%
  # Fixing date column width
  cols_width(
    players ~ gt::px(150),
    possessions ~ gt::px(115),
    logo ~ gt::px(40),
    date ~ gt::px(125),
    good_pos_rate ~ gt::px(130),
    gt::everything() ~ gt::px(75)
  ) %>%
  # Fixing column names to be 'centered'
  cols_align(
  align = c("center"), columns = everything()) %>%
  # Format percents for the rate stat
  gt::fmt_percent(
  columns = good_pos_rate,
  rows = everything(),
  decimals = 1) %>%
  # Make each row the same height
  tab_options(data_row.padding = px(1.2))

gt

gt::gtsave(data = gt,
           filename = "womens-quality-of-possessions.png",
           path = "C:/Users/Myles/OneDrive/Documents/GitHubThings/ShotQualityResearch/viz")
```




Caitlin Clark analysis (after 46 points):

```{r}
# Getting opponents for each game
school_name <- "Iowa"
player_name <- "Caitlin Clark"

opponents <- team_accurate_game_stats %>%
  rename(games_ids = game_id,
         opponent = teams) %>%
  select(games_ids, opponent) %>%
  filter(opponent != school_name) %>%
  left_join(ncaa_logos, by = c("opponent" = "logos")) %>%
  rename(opponent_logo = logo) %>%
  select(games_ids, opponent, opponent_logo)
opponents

d <- player %>%
  filter(players == player_name) %>%
  left_join(opponents) %>%
  left_join(ncaa_logos) %>%
  select(logo, opponent_logo, date, points_expected, points_scored, points_difference)

d %>%
  select(date:points_difference)
```

```{r}
gt <- d %>%
  mutate_if(is.numeric, function(x) {round(x, 2)}) %>%
  arrange(date) %>%
  gt() %>%
  text_transform(
      locations = cells_body(c(logo)),
      fn = function(x) {
        purrr::map_chr(x, ~ local_image(
          filename = as.character(.x),
          height = 30
        ))}) %>%
  text_transform(
      locations = cells_body(c(opponent_logo)),
      fn = function(x) {
        purrr::map_chr(x, ~ local_image(
          filename = as.character(.x),
          height = 30
        ))}) %>%
  cols_label(
    logo = "",
    date = "",
    opponent_logo = "",
    points_expected = "Expected",
    points_scored = "Actual",
    points_difference = "Difference"
  ) %>%
  tab_source_note(
    source_note = md("<br>Figure: @Shot_Quality")
  )  %>%
  tab_header(title = md(glue::glue("**ShotQuality discrepancies: {player_name}**")),
             subtitle = md("2021-2022 Season")) %>%
  gt_theme_538() %>%
  data_color(
    columns = c(points_difference),
    colors = scales::col_numeric(
      domain = c(-16, 16),
      alpha = .95,
      palette = c("#ff2700", "#f8fcf8", "#44ab43")  
    )) %>%
  tab_spanner(
    label = "ShotQuality Metrics",
    columns = c(points_expected:points_difference)
  ) %>%
  tab_spanner(
    label = "Matchup",
    columns = c(logo:date)
  )

gt

gt::gtsave(data = gt,
           filename = "caitlin-clark.png",
           path = "C:/Users/Myles/OneDrive/Documents/GitHubThings/ShotQualityResearch/viz")
```

#2:

```{r}
d <- running_player %>%
  arrange(desc(points)) %>%
  left_join(ncaa_logos) %>%
  mutate_at("players", Upper_Case_Names)
d
```


```{r}
domain1 <- c(quantile(running_player$good_pos_rate, .05, na.rm = T),
             quantile(running_player$good_pos_rate, .95, na.rm = T))

gt <- d %>%
  mutate_at(c("sq_ppp", "sq_points"), function(x) {round(x, 2)}) %>%
  select(logo, players, date, possessions, points, sq_points, sq_ppp, good_pos_rate) %>%
  dplyr::slice(1:15) %>%
  gt() %>%
  text_transform(
      locations = cells_body(c(logo)),
      fn = function(x) {
        purrr::map_chr(x, ~ local_image(
          filename = as.character(.x),
          height = 30
        ))}) %>%
  cols_label(
    logo = "",
    players = "",
    date = "Date",
    points = " Actual Points",
    sq_points = "Expected Points",
    possessions = "Possessions",
    good_pos_rate = "Good Possession Rate",
    # sq_passing_points_created = "SQ Passing Points"
    sq_ppp = "SQ PPP"
  ) %>%
  tab_source_note(
    source_note = md("<br>Figure: @Shot_Quality")
  )  %>%
  tab_header(title = md("**Top Scoring Performances: What were the Quality of Possessions?**"),
             subtitle = md(glue::glue("2021-2022 Season"))) %>%
  gt_theme_538() %>%
  data_color(
    columns = c(good_pos_rate),
    colors = scales::col_numeric(
      domain = domain1,
      palette = c("#ff2700", "#f8fcf8", "#44ab43")  
    )) %>%
  tab_spanner(
    label = "ShotQuality Metrics",
    columns = c(possessions:good_pos_rate)) %>%
  tab_spanner(
    label = "Player",
    columns = c(logo:date)) %>%
  # Fixing date column width
  cols_width(
    players ~ gt::px(150),
    possessions ~ gt::px(115),
    logo ~ gt::px(40),
    date ~ gt::px(125),
    good_pos_rate ~ gt::px(130),
    gt::everything() ~ gt::px(75)
  ) %>%
  # Fixing column names to be 'centered'
  cols_align(
  align = c("center"), columns = everything()) %>%
  # Format percents for the rate stat
  gt::fmt_percent(
  columns = good_pos_rate,
  rows = everything(),
  decimals = 1) %>%
  # Make each row the same height
  tab_options(data_row.padding = px(1.2)) %>%
  # Highlight row 4
  # remotes::install_github("jthomasmock/gtExtras")
  gtExtras::gt_highlight_rows(
  columns = gt::everything(),
  rows = 4,
  fill = "yellow",
  alpha = 0.8,
  font_weight = "bold",
  bold_target_only = FALSE,
  target_col = c())

gt

gt::gtsave(data = gt,
           filename = "caitlin-clark2.png",
           path = "C:/Users/Myles/OneDrive/Documents/GitHubThings/ShotQualityResearch/viz")
```



Top 20 Teams in NET ADJ SQ

```{r}
# Downloaded from website
data <- "C:/Users/Myles/Downloads/shot_quality.csv" %>%
  readr::read_csv() %>%
  janitor::clean_names()

d <- data %>%
  arrange(desc(adjusted_shot_quality)) %>%
  left_join(ncaa_logos, by = c("team_name" = "logos"))

d
```


```{r}
gt <- d %>%
  select(logo, team_name, conference.y, offensive_shot_quality, defensive_shot_quality, adjusted_shot_quality) %>%
  slice(1:15) %>%
  gt() %>%
  text_transform(
      locations = cells_body(c(logo)),
      fn = function(x) {
        purrr::map_chr(x, ~ local_image(
          filename = .x,
          height = 30))}) %>%
  cols_label(
    logo = "",
    team_name = "Team",
    conference.y = "Conference",
    offensive_shot_quality = "Offensive",
    defensive_shot_quality = "Defense",
    adjusted_shot_quality = "Net Adjusted"
  ) %>%
  tab_source_note(
    source_note = md("<br>Figure: @Shot_Quality")
  )  %>%
  tab_header(title = md("**Top 15 Teams in Net Adjusted ShotQuality**"),
             subtitle = md(glue::glue("2021-2022 Season"))) %>%
  gt_theme_538() %>%
  data_color(
    columns = c(offensive_shot_quality),
    colors = scales::col_numeric(
      domain = c(0.7, 1.2),
      alpha = .90,
      palette = c("#ff2700", "#f8fcf8", "#44ab43")  
    )) %>%
  data_color(
    columns = c(defensive_shot_quality),
    colors = scales::col_numeric(
      domain = c(1.4, 0.75),
      alpha = .90,
      palette = c("#44ab43", "#f8fcf8", "#ff2700")  
    )) %>%
  data_color(
    columns = c(adjusted_shot_quality),
    colors = scales::col_numeric(
      domain = c(-0.4, 0.4),
      alpha = .90,
      palette = c("#ff2700", "#f8fcf8", "#44ab43")  
    )) %>%
  
  tab_spanner(
    label = "ShotQuality",
    columns = c(offensive_shot_quality:adjusted_shot_quality)
  ) %>%
  tab_spanner(
    label = "Matchup",
    columns = c(logo:conference.y)
  )
gt
gt::gtsave(data = gt,
           filename = "1.png",
           path = "C:/Users/Myles/OneDrive/Documents/GitHubThings/ShotQualityResearch/viz")
```




